/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OIdRouteImport } from './routes/o.$id'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminJournalIndexRouteImport } from './routes/admin/journal/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiCheckoutConfirmRouteImport } from './routes/api/checkout/confirm'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminJournalNewRouteImport } from './routes/admin/journal/new'
import { Route as AdminJournalIdEditRouteImport } from './routes/admin/journal/$id.edit'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OIdRoute = OIdRouteImport.update({
  id: '/o/$id',
  path: '/o/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalIndexRoute = AdminJournalIndexRouteImport.update({
  id: '/admin/journal/',
  path: '/admin/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutConfirmRoute = ApiCheckoutConfirmRouteImport.update({
  id: '/api/checkout/confirm',
  path: '/api/checkout/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalNewRoute = AdminJournalNewRouteImport.update({
  id: '/admin/journal/new',
  path: '/admin/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalIdEditRoute = AdminJournalIdEditRouteImport.update({
  id: '/admin/journal/$id/edit',
  path: '/admin/journal/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/o/$id': typeof OIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/journal/$id/edit': typeof AdminJournalIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/o/$id': typeof OIdRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/journal': typeof AdminJournalIndexRoute
  '/admin/journal/$id/edit': typeof AdminJournalIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/upload': typeof ApiUploadRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/o/$id': typeof OIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/confirm': typeof ApiCheckoutConfirmRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/journal/$id/edit': typeof AdminJournalIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/subscribers'
    | '/api/orders'
    | '/api/subscribe'
    | '/api/upload'
    | '/journal/$slug'
    | '/o/$id'
    | '/admin/'
    | '/journal/'
    | '/admin/journal/new'
    | '/api/auth/$'
    | '/api/checkout/confirm'
    | '/api/stripe/webhook'
    | '/admin/journal/'
    | '/admin/journal/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/subscribers'
    | '/api/orders'
    | '/api/subscribe'
    | '/api/upload'
    | '/journal/$slug'
    | '/o/$id'
    | '/admin'
    | '/journal'
    | '/admin/journal/new'
    | '/api/auth/$'
    | '/api/checkout/confirm'
    | '/api/stripe/webhook'
    | '/admin/journal'
    | '/admin/journal/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/order'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/security'
    | '/admin/subscribers'
    | '/api/orders'
    | '/api/subscribe'
    | '/api/upload'
    | '/journal/$slug'
    | '/o/$id'
    | '/admin/'
    | '/journal/'
    | '/admin/journal/new'
    | '/api/auth/$'
    | '/api/checkout/confirm'
    | '/api/stripe/webhook'
    | '/admin/journal/'
    | '/admin/journal/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiUploadRoute: typeof ApiUploadRoute
  JournalSlugRoute: typeof JournalSlugRoute
  OIdRoute: typeof OIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  AdminJournalNewRoute: typeof AdminJournalNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutConfirmRoute: typeof ApiCheckoutConfirmRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AdminJournalIndexRoute: typeof AdminJournalIndexRoute
  AdminJournalIdEditRoute: typeof AdminJournalIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$id': {
      id: '/o/$id'
      path: '/o/$id'
      fullPath: '/o/$id'
      preLoaderRoute: typeof OIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/': {
      id: '/admin/journal/'
      path: '/admin/journal'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AdminJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/confirm': {
      id: '/api/checkout/confirm'
      path: '/api/checkout/confirm'
      fullPath: '/api/checkout/confirm'
      preLoaderRoute: typeof ApiCheckoutConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/new': {
      id: '/admin/journal/new'
      path: '/admin/journal/new'
      fullPath: '/admin/journal/new'
      preLoaderRoute: typeof AdminJournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/$id/edit': {
      id: '/admin/journal/$id/edit'
      path: '/admin/journal/$id/edit'
      fullPath: '/admin/journal/$id/edit'
      preLoaderRoute: typeof AdminJournalIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiUploadRoute: ApiUploadRoute,
  JournalSlugRoute: JournalSlugRoute,
  OIdRoute: OIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  AdminJournalNewRoute: AdminJournalNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutConfirmRoute: ApiCheckoutConfirmRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AdminJournalIndexRoute: AdminJournalIndexRoute,
  AdminJournalIdEditRoute: AdminJournalIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
